name: kilo
description: A basic console text editor written in Dart.
version: 0.1.0
author: Tim Sneath <timsneath@google.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  dart_console:
    path: ../dart_console

dev_dependencies:
  pedantic: ^1.8.0+1